### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by depado** [paked/messenger#13]
Hey there, 

With some functions, like `CallToActionsSetting` sometimes Facebook rejects it, but no error is returned by the function. So I'm thinking of adding a debug mode to your package, would that be suitable to you ?
For example, simply by outputting the result of the request, I was able to see that I was doing something wrong :
`{"error":{"message":"(#105) Number of call to actions exceeds the maximum allowed number"...}`

Or maybe parse the response and check for that error field ?

**Comment by paked** [comment]
I don't really see the point in separating any logic into a debug and non debug mode setup. If an error occurs, it should be returned through the appropriate avenue. Therefore, I'd rather resolve this issue by properly parsing Facebook's response and returning the error if one exists.

I haven't put too much thought into it, but it does seem likely that this same issue occurs in all of our other requests to the Messenger API.

Thanks for spotting this error! I would be more than happy to merge in a PR for it, I'm afraid I'll be too busy to write my own for another couple of weeks.

**Comment by depado** [comment]
Should be closed by #14

**Comment by depado** [comment]
Closing this as it's currently being fixed.

**Comment by paked** [comment]
I'd prefer to keep this issue open until your Pull Request is merged into master, if that's OK :)

**Comment by paked** [comment]
Closed by #14
