### ISSUE TITLE
Structured Responses

### ISSUE THREAD

**Issue by paked** [paked/messenger#2]
One of the cool features of the Facebook Messenger Platform is that it is possible to send "structured messages" like the following:

![https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.2178-6/12679454_228093174215421_635988637_n.png](https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xta1/t39.2178-6/12679454_228093174215421_635988637_n.png)

Currently we do not provide access to this section of the API. Obviously this functionality would be built into the `Response` structure.

I'm not quite sure what it would look like at the moment, but a start would be just to mirror to JSON structures for everything:

``` json
{
  "recipient":{
    "id":"USER_ID"
  },
  "message":{
    "attachment":{
      "type":"template",
      "payload":{
        "template_type":"button",
        "text":"What do you want to do next?",
        "buttons":[
          {
            "type":"web_url",
            "url":"https://petersapparel.parseapp.com",
            "title":"Show Website"
          },
          {
            "type":"postback",
            "title":"Start Chatting",
            "payload":"USER_DEFINED_PAYLOAD"
          }
        ]
      }
    }
  }
}
```

Then eventually we could add some sort of "API sugar", like `Response.AddButton`, `Response.AddElement`, etc.

**Comment by paked** [comment]
@panichmaxim Added support for this in #3! 🎉

**Comment by surek** [comment]
Could you please provide an example of using it?
