### ISSUE TITLE
Setting for Get Started button and Persist Menu

### ISSUE THREAD

**Issue by Walpurisnacht** [paked/messenger#31]
I think we are missing implementation of Get Started button and Persist Menu setting.
I'm setting it by extending your package, but who knows if this will be added to the framework?

**Comment by depado** [comment]
Hi @Walpurisnacht 
Please take a look at [this file](https://github.com/paked/messenger/blob/master/settings.go), this allows to set up the Get Started button and the persistent menu. I'm already using that and it works fine ☺

For example :
```go
	err = bot.Client.GreetingSetting("Hello World")
	err = bot.Client.CallToActionsSetting("existing_thread", mb)
	err = bot.Client.CallToActionsSetting("new_thread", sb)
```
Where `mb` is a `[]messenger.CallToActionsItem` and `sb` is a `[]messenger.CallToActionsItem` containing a single item.

Please tell me if that's unclear or if you need a more concrete example.

**Comment by paked** [comment]
Thanks @Depado.

I'm marking this as closed if there are no longer any issues.
