### ISSUE TITLE
Is it possible to reply or send buttons?

### ISSUE THREAD

**Issue by puzanov** [paked/messenger#35]
LIke this 
https://developers.facebook.com/docs/messenger-platform/send-messages/template/button
https://developers.facebook.com/docs/messenger-platform/send-messages/buttons
https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies

**Comment by puzanov** [comment]
Whoa! I've found it here: https://github.com/paked/messenger/blob/master/response.go
Can you share an example how to use that?

**Comment by dgellow** [comment]
@puzanov A simple example, with a button template for account linking:

```go
// Handle received messages
client.HandleMessage(func(m messenger.Message, r *messenger.Response) {
	switch strings.ToLower(m.Text) {
	case "login":
		buttons := &[]messenger.StructuredMessageButton{
			messenger.StructuredMessageButton{
				Type: "account_link",
				URL:  "https://yourSignInFormURL" ,
			},
		}
		err := r.ButtonTemplate("Connect your account", buttons, messenger.ResponseType)
		if err != nil {
			log.Println("failed to send login button:", err)
			return
		}
	}
```

**Comment by puzanov** [comment]
Thanks
