### ISSUE TITLE
send message type for compatibility

### ISSUE THREAD

**Issue by xuefeng-huang** [paked/messenger#36]
there will be a breaking change rolling out, [message type](https://developers.facebook.com/docs/messenger-platform/send-messages#messaging_types)
please add this attribute when sending messages.

**Comment by paked** [comment]
Hey!

I'm currently AFK, for at least the next week.

I'll get around to this eventually, but it won't be til at least then.

If you or someone else makes a PR I'll probably be able to merge it.

**Comment by paked** [comment]
Closed by #37
