### ISSUE TITLE
IDs from webhooks are strings and not numbers.

### ISSUE THREAD

**Issue by 1lann** [paked/messenger#4]
I don't know if they were numbers before, but at least now, user IDs from webhooks are numbers in strings. i.e. the json would be like:

``` json
{"sender":{"id":"1259905410705036"},"recipient":{"id":"1175644529126109"}, "..." }
```

This can be fixed by changing the structs to use strings instead of int64, or use something during decoding to convert it to an int64.

**Comment by paked** [comment]
Thanks for bringing this to my attention @1lann! Turns out Facebook recently changed their API. In order to keep backwards compatibility, I have left the value as an `int64` but told `json/encoding` to look for a `string`.
