### ISSUE TITLE
home_url and in_test

### ISSUE THREAD

**Issue by albttx** [paked/messenger#45]
Hello, 

First thanks ! I love the project !

How to set the `in_test` value to true ?

Needed for Extensions, see: https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/home-url

Could you provide an extensions example made with this library ? (if not, i will once i did it ;) )

**Comment by paked** [comment]
Hey!

I'm glad you're finding it useful.

Unfortunately I don't think we have any support for Chat Extensions at the moment. I don't have time to look through the documentation, but it doesn't seem like it would be that difficult to implement. I've opened an issue where this can be discussed further, which I'll close this in favour of.

**Comment by paked** [comment]
Closing in favour of #46
